blogs/blog_app/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from blog_app.api.views import BlogListView, BLogCreateView, BLogRetreiveUpdateDelete,UserApiListView,UserApiCreateView,UserRetreiveUpdateDelete
from rest_framework import routers
app_name = "blogs"
router = routers.DefaultRouter()
urlpatterns = [
    path('user_login', views.LoginFormView.as_view(), name='login'),
    path('user_logout', views.LogoutView.as_view(), name='logout'),
    path('user_signup', views.SignUpView.as_view(), name='signup'),

    #blogs
    path('',views.BlogsListView.as_view(),name="blogs_list"),
    path('<int:pk>',views.BlogsListView.as_view(),name="blogs_list_heart"),

    #user blogs 
    path('user/blogs',views.UserBlogsListView.as_view(),name="user_blogs_list"),
    path('user/blogs/<int:pk>',views.UserBlogsListView.as_view(),name="user_blogs_list_heart"),

    # blog crud
    path('user/blog/create',views.BlogCreateView.as_view(),name="blog_create"),
    path('user/blog/<int:pk>/update',views.BlogUpdateView.as_view(),name="blog_update"),
    path('user/blog/<int:pk>/delete',views.BlogDeleteView.as_view(),name="blog_delete"),

    # admin
    path('user/list',views.UserListView.as_view(),name="user_list"),
    path('user/create',views.UserCreateView.as_view(),name="user_create"),
    path('user/<int:pk>/update',views.UserUpdateView.as_view(),name="user_update"),
    path('user/<int:pk>/delete',views.UserdeleteView.as_view(),name="user_delete"),

    # api urls
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/blogs/list', BlogListView.as_view(), name="api_blog_list"),
    path('api/blogs/create', BLogCreateView.as_view(), name="api_blog_create"),
    path('api/blogs/actions/<int:pk>', BLogRetreiveUpdateDelete.as_view(), name="api_blog_actions"),

    # api admin urls
    path('api/users/list', UserApiListView.as_view(), name="api_user_list"),
    path('api/user/create', UserApiCreateView.as_view(), name="api_user_create"),
    path('api/user/actions/<int:pk>', UserRetreiveUpdateDelete.as_view(), name="api_user_actions"),
    
]

blogs/blogs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("blog_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/blog_app/models.py
from django.db import models
from django.utils.translation import gettext as _
# Create your models here.
from django.contrib.auth import get_user_model

UserModel = get_user_model()

class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class BlogModel(BaseModel):
    is_publish = models.BooleanField(default=True)
    user = models.ForeignKey(UserModel,on_delete=models.CASCADE,related_name="user")
    title = models.CharField(max_length=255,null=True,blank=True,default="")
    likes = models.ManyToManyField(UserModel, related_name="blog")
    image = models.ImageField(_("Image"),help_text="Height:480px  Width:350px",blank=True, null=True)
    content = models.TextField(default="", null=True, blank=True)
    
    def likes_count(self):
        return self.likes.count()

    def __str__(self):
        return f"{self.title}||{self.id}"

blogs/blog_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from .models import BlogModel


UserModel = get_user_model()


class LogInForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super(LogInForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"





# Sign Up Form
class SignUpForm(UserCreationForm):
    class Meta:
        model = UserModel
        fields = ("username", "email")

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        for visible in self.visible_fields():
            visible.field.widget.attrs["class"] = "form-control"


class BlogCreateForm(forms.ModelForm):
    class Meta:
        model = BlogModel
        fields = ('is_publish','user','title','image','content')
        widgets = {
        'user': forms.HiddenInput(),
        }
        

blogs/blog_app/api/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from rest_framework import generics
from rest_framework.permissions import IsAdminUser
from rest_framework import viewsets
from blog_app.models import BlogModel
from .import serializers
from django.contrib.auth import get_user_model

UserModel = get_user_model()

class BlogListView(generics.ListAPIView):
    queryset = BlogModel.objects.all()
    serializer_class = serializers.BlogSerializer

class BLogCreateView(LoginRequiredMixin,generics.CreateAPIView):
    queryset = BlogModel.objects.all()
    serializer_class = serializers.BlogSerializer
    permission_classes = []

    def perform_create(self, serializer):
        serializer.save(user=self.request.user)   

class BLogRetreiveUpdateDelete(LoginRequiredMixin,generics.RetrieveUpdateDestroyAPIView):
    queryset = BlogModel.objects.all()
    serializer_class = serializers.BlogSerializer
    permission_classes = []


    def perform_create(self, serializer):
        serializer.save(user=self.request.user) 


#  user api views
class UserApiListView(generics.ListAPIView):
    queryset = UserModel.objects.all()
    serializer_class = serializers.UserSerializer

class UserApiCreateView(generics.CreateAPIView):
    queryset = UserModel.objects.all()
    serializer_class = serializers.UserSerializer
    permission_classes = [IsAdminUser]

class UserRetreiveUpdateDelete(generics.RetrieveUpdateDestroyAPIView):
    queryset = UserModel.objects.all()
    serializer_class = serializers.UserSerializer
    permission_classes = [IsAdminUser]

        

blogs/blog_app/views.py
from django.shortcuts import redirect,get_object_or_404
from django.views.generic import FormView, ListView, View, CreateView, UpdateView, DeleteView
from .forms import LogInForm,SignUpForm,BlogCreateForm
from django.urls import reverse_lazy, reverse
from .models import BlogModel
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate, login
# Create your views here.


UserModel = get_user_model()


class LoginFormView(FormView):
    template_name = "user/user_login.html"
    form_class = LogInForm
    success_url = reverse_lazy("blogs:user_blogs_list")

    def form_valid(self, form):
        # print(form.cleaned_data)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]

        user = authenticate(username=username, password=password)
        if user:
            login(self.request, user)
            return redirect("blogs:user_blogs_list")
        return self.form_invalid(form)

class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('blogs:login')
    template_name = 'user/user_signup.html'

class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('/')

class BlogsListView(ListView):
    template_name = "blog/blogs.html"
    model = BlogModel
    context_object_name = "blogs"

    def post(self,request,pk):
        id = self.request.POST.get("pk")
        blog = get_object_or_404(BlogModel, pk=id)
        liked=False
        if blog.likes.filter(id=request.user.id).exists():
            blog.likes.remove(request.user)
            liked = False
        else:
            blog.likes.add(request.user)
            liked = True

        return HttpResponseRedirect(reverse("blogs:blogs_list"))
        

class UserBlogsListView(ListView):
    template_name = "blog/user_blogs.html"
    model = BlogModel
    context_object_name = "blogs"   
    
    def get_queryset(self):
        qs = super().get_queryset() 
        return qs.filter(user=self.request.user) 
    def post(self,request,pk):
        id = self.request.POST.get("pk")
        blog = get_object_or_404(BlogModel, pk=id)
        liked=False
        if blog.likes.filter(id=request.user.id).exists():
            blog.likes.remove(request.user)
            liked = False
        else:
            blog.likes.add(request.user)
            liked = True
        return HttpResponseRedirect(reverse("blogs:user_blogs_list"))

# blog Views

class BlogCreateView(LoginRequiredMixin, CreateView):
    form_class = BlogCreateForm
    template_name = "blog/user_blog_create.html"

    def get_initial(self, *args, **kwargs):
        initial = super(BlogCreateView, self).get_initial(**kwargs)
        initial['user'] = self.request.user
        return initial

    def get_success_url(self):
        return reverse_lazy("blogs:user_blogs_list")

class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = BlogModel
    form_class = BlogCreateForm
    template_name = "blog/user_blog_update.html"
    def get_success_url(self):
        return reverse_lazy("blogs:user_blogs_list")
    
class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = BlogModel
    template_name = "blog_app/user_blog_delete.html"
    def get_success_url(self):
        return reverse_lazy("blogs:user_blogs_list")        


# user related views

class UserListView(LoginRequiredMixin, ListView):
    template_name = "user/user_list.html"
    model = UserModel
    context_object_name = "users"


class UserCreateView(LoginRequiredMixin,CreateView):
    form_class = SignUpForm
    template_name = "user/user_create.html"

    def get_success_url(self):
        return reverse_lazy("blogs:user_list")

class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = UserModel
    form_class = SignUpForm
    template_name = "user/user_update.html"
    def get_success_url(self):
        return reverse_lazy("blogs:user_list")

class UserdeleteView(LoginRequiredMixin, DeleteView):
    model = UserModel
    template_name = "user/user_delete.html"
    def get_success_url(self):
        return reverse_lazy("blogs:user_list")      

blogs/templates/blog_app/blogs.html
{% extends 'base.html' %}
{% block css %}
<style>
	.heart{
        font-size:30px;
    }
    .heart-btn{
        background: transparent;
        border: none !important;
        font-size:0;
		padding-top:115px;
    }
</style>
{% endblock %}
{% block body %}
<section id="trainer" class="parallax-section">
	<div class="container">
		<div class="row">
            <div class="wow fadeInUp col-md-12 col-sm-12" data-wow-delay="1.3s">
                <h2>Blogs</h2>
			</div>
            {% for blog in blogs %}
            {% if blog.is_publish %}
			<div class="wow fadeInUp col-md-4 col-sm-6" data-wow-delay="1.9s">
				<div class="trainer-thumb">
					<img  src="{{blog.image.url}}" class="img-responsive" alt="Trainer">
						<div class="trainer-overlay">
							<div class="trainer-des">
								<h2>{{blog.title}}</h2>
							</div>
							{% if request.user.is_authenticated %}
								<div class="hearts">
									<form method="POST" action="{% url 'blogs:blogs_list_heart' blog.id %}">
										{% csrf_token %}
										<button class="heart-btn" type="submit" name="pk" value="{{blog.id}}">
											{% if request.user in blog.likes.all %}
												<i style="color:red!important;" class="heart fa fa-heart" aria-hidden="true"></i>
											{% else %}
												<i class="heart fa fa-heart" aria-hidden="true"></i>
											{% endif %}
										</button>
									</form>
								</div>
								<div>{{blog.likes_count}}</div>
							{% else %}
								<button class="heart-btn">
									<i class="heart fa fa-heart" aria-hidden="true"></i>
								</button>
								<div>{{blog.likes_count}}</div>
							{% endif %}
						</div>
				</div>
				<p>{{blog.content|safe}}.</p>
			</div>
			{% endif %}
			{% endfor %}

		</div>
	</div>
</section>
{% endblock%}

blogs/templates/blog_app/user_blogs.html
{% extends 'base.html' %}
{% block css %}
<style>
    .blog-crud{
        margin:10px;
        font-size:30px;
    }
    .heart{
        font-size:30px;
    }
    .heart-btn{
        background: transparent;
        border: none !important;
        font-size:0;
    }
</style>
{% endblock %}
{% block body %}
<section id="trainer" class="parallax-section">
	<div class="container">
		<div class="row">
            <div class="wow fadeInUp col-md-12 col-sm-12" data-wow-delay="1.3s">
                <h2>Your  Blogs</h2>
			</div>
            {% for blog in blogs %}
                <div class="wow fadeInUp col-md-4 col-sm-6" data-wow-delay="1.9s">
                    <div class="trainer-thumb">
                        <img  src="{{blog.image.url}}" class="img-responsive" alt="Trainer">
                            <div class="trainer-overlay">
                            
                                <div class="blog-crud text-right"><a href="{% url 'blogs:blog_update' blog.id%} "><i class="fa fa-edit"></i></a></div>
                                <div class="blog-crud text-right"><a href="{% url 'blogs:blog_delete' blog.id %} "><i class="fa fa-trash" aria-hidden="true"></i></a></div>
                                <div class="trainer-des">
                                    <h2>{{blog.title}}</h2>
                                </div>
                                <div class="hearts">
                                    <form method="POST" action="{% url 'blogs:user_blogs_list_heart' blog.id %}">
                                        {% csrf_token %}
                                        <button class="heart-btn" type="submit" name="pk" value="{{blog.id}}">
                                            {% if request.user in blog.likes.all %}
                                                <i style="color:red!important;" class="heart fa fa-heart" aria-hidden="true"></i>
                                            {% else %}
                                                <i class="heart fa fa-heart" aria-hidden="true"></i>
                                            {% endif %}
                                        </button>
                                    </form>
                                </div>
                                <div>{{blog.likes_count}}</div>
                               
                        </div>
                    </div>
                    <p>{{blog.content|safe|truncatechars:100}}.</p>
                </div>
			{% endfor %}

		</div>
	</div>
</section>
{% endblock%}

blogs/templates/blog_app/user_list.html
{% extends 'base.html' %}
{% block css %}
<style>
    body{
        padding:120px;
    }
</style>
{% endblock %}
{% block body %}
<div id="container">
    <a href="{% url 'blogs:user_create' %}"><button class="btn btn-primary">create new user</button></a>
    <table class="table">
        <thead>
          <tr>     
            <th scope="col">Sr.no</th>
            <th scope="col">User Name</th>
            <th scope="col">Email</th>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>   
                    <th scope="col">{{forloop.counter}}</th>
                <td>{{user.username}}</td> 
                <td>{{user.email}}</td> 
                <td>{{issue.priority}}</td> 
                <td><a href="{% url 'blogs:user_update' user.id%}"><i class="fa fa-edit"></i></a></td>   
                <td><a href="{% url 'blogs:user_delete' user.id%}"><i class="fa fa-trash" aria-hidden="true"></i></a></td> 
                </tr>
          {% endfor %}
        </tbody>
      </table>
</div>    
{% endblock  %}