blogs/blog_app/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from blog_app.api.views import BlogListView, BLogCreateView, BLogRetreiveUpdateDelete,UserApiListView,UserApiCreateView,UserRetreiveUpdateDelete
from rest_framework import routers
app_name = "blogs"
router = routers.DefaultRouter()
urlpatterns = [
    path('user_login', views.LoginFormView.as_view(), name='login'),
    path('user_logout', views.LogoutView.as_view(), name='logout'),
    path('user_signup', views.SignUpView.as_view(), name='signup'),

    #blogs
    path('',views.BlogsListView.as_view(),name="blogs_list"),
    path('<int:pk>',views.BlogsListView.as_view(),name="blogs_list_heart"),

    #user blogs 
    path('user/blogs',views.UserBlogsListView.as_view(),name="user_blogs_list"),
    path('user/blogs/<int:pk>',views.UserBlogsListView.as_view(),name="user_blogs_list_heart"),

    # blog crud
    path('user/blog/create',views.BlogCreateView.as_view(),name="blog_create"),
    path('user/blog/<int:pk>/update',views.BlogUpdateView.as_view(),name="blog_update"),
    path('user/blog/<int:pk>/delete',views.BlogDeleteView.as_view(),name="blog_delete"),

    # admin
    path('user/list',views.UserListView.as_view(),name="user_list"),
    path('user/create',views.UserCreateView.as_view(),name="user_create"),
    path('user/<int:pk>/update',views.UserUpdateView.as_view(),name="user_update"),
    path('user/<int:pk>/delete',views.UserdeleteView.as_view(),name="user_delete"),

    # api urls
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/blogs/list', BlogListView.as_view(), name="api_blog_list"),
    path('api/blogs/create', BLogCreateView.as_view(), name="api_blog_create"),
    path('api/blogs/actions/<int:pk>', BLogRetreiveUpdateDelete.as_view(), name="api_blog_actions"),

    # api admin urls
    path('api/users/list', UserApiListView.as_view(), name="api_user_list"),
    path('api/user/create', UserApiCreateView.as_view(), name="api_user_create"),
    path('api/user/actions/<int:pk>', UserRetreiveUpdateDelete.as_view(), name="api_user_actions"),
    
]

blogs/blogs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("blog_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/templates/blog/blogs.html
{% extends 'base.html' %}
{% block css %}
<style>
	.heart{
        font-size:30px;
    }
    .heart-btn{
        background: transparent;
        border: none !important;
        font-size:0;
		padding-top:115px;
    }
</style>
{% endblock %}
{% block body %}
<section id="trainer" class="parallax-section">
	<div class="container">
		<div class="row">
            <div class="wow fadeInUp col-md-12 col-sm-12" data-wow-delay="1.3s">
                <h2>Blogs</h2>
			</div>
            {% for blog in blogs %}
            {% if blog.is_publish %}
			<div class="wow fadeInUp col-md-4 col-sm-6" data-wow-delay="1.9s">
				<div class="trainer-thumb">
					{% if blog.image %}
					<img  src="{{blog.image.url}}" class="img-responsive" alt="Trainer">
					{% endif %}
						<div class="trainer-overlay">
							{% if blog.title %}
							<div class="trainer-des">
								<h2>{{blog.title}}</h2>
							</div>
							{% endif %}
							{% if request.user.is_authenticated %}
								<div class="hearts">
									<form method="POST" action="{% url 'blogs:blogs_list_heart' blog.id %}">
										{% csrf_token %}
										<button class="heart-btn" type="submit" name="pk" value="{{blog.id}}">
											{% if request.user in blog.likes.all %}
												<i style="color:red!important;" class="heart fa fa-heart" aria-hidden="true"></i>
											{% else %}
												<i class="heart fa fa-heart" aria-hidden="true"></i>
											{% endif %}
										</button>
									</form>
								</div>
								<div>{{blog.likes_count}}</div>
							{% else %}
								<button class="heart-btn">
									<i class="heart fa fa-heart" aria-hidden="true"></i>
								</button>
								<div>{{blog.likes_count}}</div>
							{% endif %}
						</div>
				</div>
				{% if blog.content %}
					<p>{{blog.content|safe|truncatechars:100}}.</p>
				{% endif %}
			</div>
			{% endif %}
			{% endfor %}

		</div>
	</div>
</section>
{% endblock%}

blogs/templates/blog/user_blog_create.html
{% extends 'base.html' %}
{% block css %}
<style>
    body{
        padding-top:100px;
        align-content:center;
    }
    form{
        display:flex;
        justify-content:center;
    }
   
</style>
{% endblock %}
{% block body %}
<div class="container">
    <h2 class="text-center">Create New Blog </h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="">
            {% for hidden in form.hidden_fields %}
            {{hidden}}
            {% endfor %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Create</button>
        </div>
       
    </form>
</div>
{% endblock %}

blogs/templates/blog/user_blog_delete.html
{% extends 'base.html' %}
{% block css %}
<style>
    body{
        padding-top:100px;
        align-content:center;
    }
    form{
        display:flex;
        justify-content:center;
    }
</style>
{% endblock %}
{% block body %}
    <div class="container text-center">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-lg-6 grid-margin stretch-card">   
                <div class="card">
                    <div class="card-body">
                    <h5> Hi..{{request.user.username}}</h5><br> 
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <p>Are you sure you want to delete "{{ object }}" Blog?</p> 
                            </tr>
                        </tbody>
                    </table>
                    <button type = "submit" class="btn btn-danger">Delete</button>
                </div>
            </div>
        </form>
    </div>    
{% endblock %}

blogs/templates/blog/user_blog_update.html
{% extends 'base.html' %}
{% block css %}
<style>
    body{
        padding-top:100px;
        align-content:center;
    }
    form{
        display:flex;
        justify-content:center;
    }
   
</style>
{% endblock %}
{% block body %}
<div class="container">
    <h2 class="text-center">Update Blog </h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="">
            {{form.as_p}}
            <button type="submit" class="btn btn-primary" >Update</button>
        </div>
       
    </form>
</div>
{% endblock %}

blogs/templates/blog/user_blogs.html
{% extends 'base.html' %}
{% block css %}
<style>
    .blog-crud{
        margin:10px;
        font-size:30px;
    }
    .heart{
        font-size:30px;
    }
    .heart-btn{
        background: transparent;
        border: none !important;
        font-size:0;
    }
</style>
{% endblock %}
{% block body %}
<section id="trainer" class="parallax-section">
	<div class="container">
		<div class="row">
            <div class="wow fadeInUp col-md-12 col-sm-12" data-wow-delay="1.3s">
                <h2>Your  Blogs</h2>
			</div>
            {% for blog in blogs %}
                <div class="wow fadeInUp col-md-4 col-sm-6" data-wow-delay="1.9s">
                    <div class="trainer-thumb">
                        {% if blog.image %}
                        <img  src="{{blog.image.url}}" class="img-responsive" alt="Trainer">
                        {% endif %}
                            <div class="trainer-overlay">
                            
                                <div class="blog-crud text-right"><a href="{% url 'blogs:blog_update' blog.id%} "><i class="fa fa-edit"></i></a></div>
                                <div class="blog-crud text-right"><a href="{% url 'blogs:blog_delete' blog.id %} "><i class="fa fa-trash" aria-hidden="true"></i></a></div>
                                <div class="blog-crud text-right"><a href="{% url 'blogs:api_blog_actions' blog.id%} "><i class="fa fa-edit"></i>api</a></div>
                                {% if blog.title %}
                                    <div class="trainer-des">
                                        <h2>{{blog.title}}</h2>
                                    </div>
                                {% endif %}
                                <div class="hearts">
                                    <form method="POST" action="{% url 'blogs:user_blogs_list_heart' blog.id %}">
                                        {% csrf_token %}
                                        <button class="heart-btn" type="submit" name="pk" value="{{blog.id}}">
                                            {% if request.user in blog.likes.all %}
                                                <i style="color:red!important;" class="heart fa fa-heart" aria-hidden="true"></i>
                                            {% else %}
                                                <i class="heart fa fa-heart" aria-hidden="true"></i>
                                            {% endif %}
                                        </button>
                                    </form>
                                </div>
                                <div>{{blog.likes_count}}</div>
                               
                        </div>
                    </div>
                    {% if blog.content %}
                        <p>{{blog.content|safe|truncatechars:100}}.</p>
                    {% endif %}
                </div>
			{% endfor %}

		</div>
	</div>
</section>
{% endblock%}