blogs/blog_app/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from blog_app.api.views import BlogListView, BLogCreateView, BLogRetreiveUpdateDelete,UserApiListView,UserApiCreateView,UserRetreiveUpdateDelete
from rest_framework import routers
app_name = "blogs"
router = routers.DefaultRouter()
urlpatterns = [
    path('user_login', views.LoginFormView.as_view(), name='login'),
    path('user_logout', views.LogoutView.as_view(), name='logout'),
    path('user_signup', views.SignUpView.as_view(), name='signup'),

    #blogs
    path('',views.BlogsListView.as_view(),name="blogs_list"),
    path('<int:pk>',views.BlogsListView.as_view(),name="blogs_list_heart"),

    #user blogs 
    path('user/blogs',views.UserBlogsListView.as_view(),name="user_blogs_list"),
    path('user/blogs/<int:pk>',views.UserBlogsListView.as_view(),name="user_blogs_list_heart"),

    # blog crud
    path('user/blog/create',views.BlogCreateView.as_view(),name="blog_create"),
    path('user/blog/<int:pk>/update',views.BlogUpdateView.as_view(),name="blog_update"),
    path('user/blog/<int:pk>/delete',views.BlogDeleteView.as_view(),name="blog_delete"),

    # admin
    path('user/list',views.UserListView.as_view(),name="user_list"),
    path('user/create',views.UserCreateView.as_view(),name="user_create"),
    path('user/<int:pk>/update',views.UserUpdateView.as_view(),name="user_update"),
    path('user/<int:pk>/delete',views.UserdeleteView.as_view(),name="user_delete"),

    # api urls
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/blogs/list', BlogListView.as_view(), name="api_blog_list"),
    path('api/blogs/create', BLogCreateView.as_view(), name="api_blog_create"),
    path('api/blogs/actions/<int:pk>', BLogRetreiveUpdateDelete.as_view(), name="api_blog_actions"),

    # api admin urls
    path('api/users/list', UserApiListView.as_view(), name="api_user_list"),
    path('api/user/create', UserApiCreateView.as_view(), name="api_user_create"),
    path('api/user/actions/<int:pk>', UserRetreiveUpdateDelete.as_view(), name="api_user_actions"),
    
]

blogs/blogs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("blog_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/templates/user/user_create.html
{% extends 'base.html' %}
{% block css %}
<style>
    body{
        padding-top:100px;
        align-content:center;
    }
    form{
        display:flex;
        justify-content:center;
    }
   
</style>
{% endblock %}
{% block body %}
<div class="container">
    <h2 class="text-center">Create New User </h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="">
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Create</button>
        </div>
       
    </form>
</div>
{% endblock %}

blogs/templates/user/user_delete.html
{% extends 'base.html' %}
{% block css %}
<style>
    body{
        padding-top:100px;
        align-content:center;
    }
    form{
        display:flex;
        justify-content:center;
    }
</style>
{% endblock %}
{% block body %}
    <div class="container text-center">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="col-lg-6 grid-margin stretch-card">   
                <div class="card">
                    <div class="card-body">
                    <h5> Hi..{{request.user.username}}</h5><br> 
                    <table class="table table-hover">
                        <tbody>
                            <tr>
                                <p>Are you sure you want to delete "{{ object }}" User?</p> 
                            </tr>
                        </tbody>
                    </table>
                    <button type = "submit" class="btn btn-danger">Delete</button>
                </div>
            </div>
        </form>
    </div>    
{% endblock %}

blogs/templates/user/user_list.html
{% extends 'base.html' %}
{% block css %}
<style>
    body{
        padding:120px;
    }
</style>
{% endblock %}
{% block body %}
<div id="container">
    <a href="{% url 'blogs:user_create' %}"><button class="btn btn-primary">create new user</button></a>
    <table class="table">
        <thead>
          <tr>     
            <th scope="col">Sr.no</th>
            <th scope="col">User Name</th>
            <th scope="col">Email</th>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>   
                    <th scope="col">{{forloop.counter}}</th>
                <td>{{user.username}}</td> 
                <td>{{user.email}}</td> 
                <td>{{issue.priority}}</td> 
                <td><a href="{% url 'blogs:user_update' user.id%}"><i class="fa fa-edit"></i></a></td>   
                <td><a href="{% url 'blogs:user_delete' user.id%}"><i class="fa fa-trash" aria-hidden="true"></i></a></td> 
                <td><a href="{% url 'blogs:api_user_actions' user.id%}"><i class="fa fa-edit">api</i></a></td>   

                </tr>
          {% endfor %}
        </tbody>
      </table>
</div>    
{% endblock  %}

blogs/templates/user/user_login.html
{% extends 'base.html' %}
{% load static %}
{% block body %}
<style>
    .navbar{
        display:none;
    }
    .fs-6 a{
        font-size:16px;
    }
</style>
<div class="wrapper">
    <div class="logo">
        <img src="{% static 'images/login.svg' %} " alt="">
    </div>
    <div class="text-center mt-4 name">
        Login
    </div>
    <div class="p-3 mt-3">
        {% if form.errors%}
           {{forms.errors}}
        {% endif %}
      
        <form method="POST" >
            {% csrf_token %}
            {{form.as_p}}
       
        <div class="text-center fs-6">
            <button type="submit" value="Submit" class="btn btn-primary mb-3">Login</button>
        </div>
        </form>
            
    </div>  
    <div class="text-center fs-6">
        <a href="/">Home Page</a> or <a href="{% url 'blogs:signup' %} ">Sign up</a>
    </div>
</div>
{% endblock%}

blogs/templates/user/user_signup.html
{% extends 'base.html' %}

{% block title %}Sign Page{% endblock title %}

{% block body %} 
<style>
    .navbar{
        display:none;
    }
</style>
<div class="container">

    <h2 class="text-center">SignUp</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
        <br><br>
    </form>
</div>
{% endblock  %}

blogs/templates/user/user_update.html
{% extends 'base.html' %}
{% block css %}
<style>
    body{
        padding-top:100px;
        align-content:center;
    }
    form{
        display:flex;
        justify-content:center;
    }
   
</style>
{% endblock %}
{% block body %}
<div class="container">
    <h2 class="text-center">Update Blog </h2>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="">
            {{form.as_p}}
            <button type="submit" class="btn btn-primary" >Update</button>
        </div>
       
    </form>
</div>
{% endblock %}