blogs/blog_app/urls.py
from django.contrib import admin
from django.urls import path,include
from .import views
from blog_app.api.views import BlogListView, BLogCreateView, BLogRetreiveUpdateDelete,UserApiListView,UserApiCreateView,UserRetreiveUpdateDelete
from rest_framework import routers
app_name = "blogs"
router = routers.DefaultRouter()
urlpatterns = [
    path('user_login', views.LoginFormView.as_view(), name='login'),
    path('user_logout', views.LogoutView.as_view(), name='logout'),
    path('user_signup', views.SignUpView.as_view(), name='signup'),

    #blogs
    path('',views.BlogsListView.as_view(),name="blogs_list"),
    path('<int:pk>',views.BlogsListView.as_view(),name="blogs_list_heart"),

    #user blogs 
    path('user/blogs',views.UserBlogsListView.as_view(),name="user_blogs_list"),
    path('user/blogs/<int:pk>',views.UserBlogsListView.as_view(),name="user_blogs_list_heart"),

    # blog crud
    path('user/blog/create',views.BlogCreateView.as_view(),name="blog_create"),
    path('user/blog/<int:pk>/update',views.BlogUpdateView.as_view(),name="blog_update"),
    path('user/blog/<int:pk>/delete',views.BlogDeleteView.as_view(),name="blog_delete"),

    # admin
    path('user/list',views.UserListView.as_view(),name="user_list"),
    path('user/create',views.UserCreateView.as_view(),name="user_create"),
    path('user/<int:pk>/update',views.UserUpdateView.as_view(),name="user_update"),
    path('user/<int:pk>/delete',views.UserdeleteView.as_view(),name="user_delete"),

    # api urls
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('api/blogs/list', BlogListView.as_view(), name="api_blog_list"),
    path('api/blogs/create', BLogCreateView.as_view(), name="api_blog_create"),
    path('api/blogs/actions/<int:pk>', BLogRetreiveUpdateDelete.as_view(), name="api_blog_actions"),

    # api admin urls
    path('api/users/list', UserApiListView.as_view(), name="api_user_list"),
    path('api/user/create', UserApiCreateView.as_view(), name="api_user_create"),
    path('api/user/actions/<int:pk>', UserRetreiveUpdateDelete.as_view(), name="api_user_actions"),
    
]

blogs/blogs/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("blog_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        
        <link rel="stylesheet" href=" {% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href=" {% static 'css/animate.css' %} ">
        <link rel="stylesheet" href=" {% static 'css/font-awesome.min.css' %}">
        {% comment %} <link rel="stylesheet" href=" {% static 'css/owl.theme.css' %}"> {% endcomment %}
        <link rel="stylesheet" href=" {% static 'css/login.css' %}">
       

<!-- Main css -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<!-- Google Font -->
<link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Lora:700italic' rel='stylesheet' type='text/css'>
       
        <script src="https://use.fontawesome.com/8707e32926.js"></script>
        {% block css %}
        {% endblock %}
    </head>
    <body>
        <div class="navbar navbar-default navbar-fixed-top sticky-navigation" role="navigation">
            <div class="container">
        
                <div class="navbar-header">
                    <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon icon-bar"></span>
                        <span class="icon icon-bar"></span>
                        <span class="icon icon-bar"></span>
                    </button>
                    <a href="/" class="navbar-brand">Blogs</a>
                </div>
                <div class="collapse navbar-collapse">
                    {% if request.user.is_authenticated and request.user.is_superuser%}
                        <ul class="nav navbar-nav navbar-right main-navigation">
                            <li><a class="smoothScroll"><i class="fa fa-user" aria-hidden="true"></i>{{request.user.username}}</a></li>
                            <li><a href="{% url 'blogs:blog_create' %} " class="smoothScroll"><i class="fa fa-plus" aria-hidden="true"></i>Blog</a></li>
                            <li><a href="{% url 'blogs:api_blog_create' %} " class="smoothScroll"><i class="fa fa-plus" aria-hidden="true"></i>api</a></li>

                            <li><a href="{% url 'blogs:user_list' %} " class="smoothScroll">User list</a></li>
                            <li><a href=" {% url 'blogs:user_blogs_list' %} " class="smoothScroll">My blogs</a></li>
                            <li><a href=" {% url 'blogs:logout' %} " class="smoothScroll">Logout</a></li>
                        </ul>
                    {% elif request.user.is_authenticated %}    
                        <ul class="nav navbar-nav navbar-right main-navigation">
                            <li><a class="smoothScroll"><i class="fa fa-user" aria-hidden="true"></i>{{request.user.username}}</a></li>
                            <li><a href="{% url 'blogs:blog_create' %} " class="smoothScroll"><i class="fa fa-plus" aria-hidden="true"></i>Blog</a></li>
                            <li><a href="{% url 'blogs:api_blog_create' %} " class="smoothScroll"><i class="fa fa-plus" aria-hidden="true"></i>api</a></li>

                            <li><a href=" {% url 'blogs:user_blogs_list' %} " class="smoothScroll">My blogs</a></li>
                            <li><a href=" {% url 'blogs:logout' %} " class="smoothScroll">Logout</a></li>
                        </ul>
                    {% else %}
                    <ul class="nav navbar-nav navbar-right main-navigation">
                        <li><a class="smoothScroll"></a></li>
                        <li><a href=" {% url 'blogs:login' %} " class="smoothScroll">Login</a></li>
                    </ul>
                    {% endif %}
                </div>
        
            </div>
        </div>
        {% block body %}
        <!-- content will add here -->
        {% endblock %}
        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js'%}"></script>
        
        {% block js %}
        {% endblock %}
    </body>
</html>